### PR TITLE
Rename Prism to Cortex

### PR DESCRIPTION
**Pull request by jml**
Part of #70 

Not entirely mechanical, as vendored things use "prism" to mean something else.

---
This change is [Reviewable](https://reviewable.io/reviews/weaveworks/prism/71)

### CODE REVIEW

**Comment by tomwilkie** [comment]
```
$ f prism
./chunk/chunk_cache.go:		Namespace: "prism",
./chunk/chunk_cache.go:		Namespace: "prism",
./chunk/chunk_cache.go:		Namespace: "prism",
```

Also some references in `ui/bindata.go`

**Comment by tomwilkie** [comment]
LGTM!  Have you renamed/made a new repo on docker hub?

**Comment by jml** [comment]
Docker Hub, yes.

**Comment by jml** [comment]
* chunk_cache fixed (forgot to do search & replace after rebasing)
* bindata.go fixed (forgot to `git ls-files |grep prism`)

Rebased for posterity

**Pull request merged**
